GET http://localhost:1234/pokemon/ditto

###
GET http://localhost:1234/bebelindo.jpg

###

POST  http://localhost:1234/pokemon
Content-Type: application/json

  {
    "name": "ditto",
    "type": "normal",
    "moves":[
      "transform"
    ]
  }

###
PUT   http://localhost:1234/pokemon
Content-Type: application/json

  {
    "name": "ditto",
    "type": "normal",
    "moves":[
      "transform"
    ]
  }


